# Generated by Django 4.0.5 on 2022-06-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkapp.parkslot')),
                ('phonenumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkapp.profile')),
            ],
        ),
    ]
