# Generated by Django 4.0.5 on 2022-06-21 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='parkslots/')),
                ('booked', models.BooleanField(default=False)),
                ('booked_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkapp.bookedslot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
