# Generated by Django 4.0.5 on 2022-06-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0002_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='parkslot',
            new_name='park_slot',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
