# Generated by Django 4.0.5 on 2022-06-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0002_alter_profile_parking_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkslot',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='parkslot',
            name='booked_slot',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parking_slot',
        ),
        migrations.DeleteModel(
            name='BookedSlot',
        ),
    ]
